-- 04_queries.sql
-- This script contains complex queries demonstrating various SQL operations.

USE HotelReservationDB;
GO

-- 1. Reservation details with customer and room info.
-- Demonstrates: INNER JOIN
-- Retrieves a comprehensive view of each reservation, including customer names and room details.
SELECT 
    r.ReservationID, 
    c.FirstName + ' ' + c.LastName AS CustomerName, 
    rm.RoomNumber, 
    rc.CategoryName,
    r.CheckInDate, 
    r.CheckOutDate, 
    r.ReservationStatus
FROM 
    Reservations r
INNER JOIN 
    Customers c ON r.CustomerID = c.CustomerID
INNER JOIN 
    Rooms rm ON r.RoomID = rm.RoomID
INNER JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID;
GO

-- 2. Available rooms for a given date range (e.g., '2026-06-01' to '2026-06-10').
-- Demonstrates: Nested subquery
-- Finds all rooms that do not have an active or booked reservation overlapping with the given dates.
SELECT 
    rm.RoomNumber, 
    rc.CategoryName, 
    rc.BasePrice
FROM 
    Rooms rm
INNER JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID
WHERE 
    rm.RoomID NOT IN (
        SELECT RoomID 
        FROM Reservations 
        WHERE (CheckInDate < '2026-06-10' AND CheckOutDate > '2026-06-01')
        AND ReservationStatus IN ('Booked', 'CheckedIn')
    );
GO

-- 3. Customer booking history.
-- Demonstrates: LEFT JOIN, ORDER BY
-- Lists all customers and their reservations. Customers without reservations will also appear (with NULL reservation data).
SELECT 
    c.CustomerID, 
    c.FirstName, 
    c.LastName, 
    r.ReservationID, 
    r.CheckInDate, 
    r.ReservationStatus
FROM 
    Customers c
LEFT JOIN 
    Reservations r ON c.CustomerID = r.CustomerID
ORDER BY 
    c.LastName, r.CheckInDate DESC;
GO

-- 4. Revenue by room category.
-- Demonstrates: GROUP BY, Aggregate function (SUM)
-- Calculates the total expected revenue generated by each room category, excluding cancelled bookings.
SELECT 
    rc.CategoryName, 
    SUM(r.TotalAmount) AS TotalRevenue
FROM 
    Reservations r
INNER JOIN 
    Rooms rm ON r.RoomID = rm.RoomID
INNER JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID
WHERE 
    r.ReservationStatus != 'Cancelled'
GROUP BY 
    rc.CategoryName
ORDER BY 
    TotalRevenue DESC;
GO

-- 5. Occupancy count by room category.
-- Demonstrates: RIGHT JOIN, Aggregate function (COUNT)
-- Counts the number of times rooms in each category have been booked.
-- RIGHT JOIN ensures all categories are listed even if they have 0 bookings.
SELECT 
    rc.CategoryName, 
    COUNT(r.ReservationID) AS NumberOfBookings
FROM 
    Reservations r
INNER JOIN 
    Rooms rm ON r.RoomID = rm.RoomID
RIGHT JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID
GROUP BY 
    rc.CategoryName;
GO

-- 6. Pending or partial payments.
-- Demonstrates: Filtering on multiple joined tables
-- Lists all payments that are currently marked as 'Pending', along with the customer who owes it.
SELECT 
    c.FirstName + ' ' + c.LastName AS CustomerName,
    b.BillID,
    b.TotalAmount AS BillAmount,
    p.AmountPaid,
    p.PaymentStatus,
    p.PaymentDate
FROM 
    Payments p
INNER JOIN 
    Bills b ON p.BillID = b.BillID
INNER JOIN 
    Reservations r ON b.ReservationID = r.ReservationID
INNER JOIN 
    Customers c ON r.CustomerID = c.CustomerID
WHERE 
    p.PaymentStatus = 'Pending';
GO

-- 7. Cancelled reservations.
-- Demonstrates: Filtering
-- Retrieves all reservations that were cancelled, and the customer who cancelled them.
SELECT 
    r.ReservationID, 
    c.FirstName + ' ' + c.LastName AS CustomerName, 
    r.CheckInDate, 
    r.CheckOutDate
FROM 
    Reservations r
INNER JOIN 
    Customers c ON r.CustomerID = c.CustomerID
WHERE 
    r.ReservationStatus = 'Cancelled';
GO

-- 8. Most frequently booked rooms.
-- Demonstrates: GROUP BY, ORDER BY, TOP
-- Finds the top 5 rooms that have been reserved the most number of times.
SELECT TOP 5
    rm.RoomNumber, 
    rc.CategoryName, 
    COUNT(r.ReservationID) AS TimesBooked
FROM 
    Rooms rm
INNER JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID
LEFT JOIN 
    Reservations r ON rm.RoomID = r.RoomID
GROUP BY 
    rm.RoomNumber, rc.CategoryName
ORDER BY 
    TimesBooked DESC;
GO

-- 9. Customers with more than one reservation.
-- Demonstrates: GROUP BY, HAVING
-- Identifies loyal customers who have made more than 1 booking.
SELECT 
    c.CustomerID, 
    c.FirstName, 
    c.LastName, 
    COUNT(r.ReservationID) AS TotalReservations
FROM 
    Customers c
INNER JOIN 
    Reservations r ON c.CustomerID = r.CustomerID
GROUP BY 
    c.CustomerID, c.FirstName, c.LastName
HAVING 
    COUNT(r.ReservationID) > 1;
GO

-- 10. Monthly revenue for the year 2026.
-- Demonstrates: Date functions, GROUP BY, Aggregate function
-- Calculates the total successful payments grouped by month for financial reporting.
SELECT 
    MONTH(b.BillDate) AS BillMonth, 
    SUM(p.AmountPaid) AS MonthlyRevenue
FROM 
    Bills b
INNER JOIN 
    Payments p ON b.BillID = p.BillID
WHERE 
    YEAR(b.BillDate) = 2026 AND p.PaymentStatus = 'Completed'
GROUP BY 
    MONTH(b.BillDate)
ORDER BY 
    BillMonth;
GO

-- 11. Rooms not booked yet.
-- Demonstrates: FULL OUTER JOIN, IS NULL filtering
-- Finds any rooms that do not have any associated records in the Reservations table.
SELECT 
    rm.RoomNumber, 
    rc.CategoryName
FROM 
    Rooms rm
INNER JOIN
    RoomCategories rc ON rm.CategoryID = rc.CategoryID
FULL OUTER JOIN 
    Reservations r ON rm.RoomID = r.RoomID
WHERE 
    r.ReservationID IS NULL;
GO

-- 12. Highest bill amount per customer.
-- Demonstrates: Correlated subquery
-- For each customer, finds the bill that has the maximum total amount among all their bills.
SELECT 
    c.FirstName, 
    c.LastName, 
    b1.TotalAmount AS HighestBill
FROM 
    Customers c
INNER JOIN 
    Reservations r ON c.CustomerID = r.CustomerID
INNER JOIN 
    Bills b1 ON r.ReservationID = b1.ReservationID
WHERE 
    b1.TotalAmount = (
        SELECT MAX(b2.TotalAmount)
        FROM Bills b2
        INNER JOIN Reservations r2 ON b2.ReservationID = r2.ReservationID
        WHERE r2.CustomerID = c.CustomerID
    );
GO

-- 13. Room details with the overall average base price.
-- Demonstrates: Scalar subquery
-- Shows each room's category price alongside the average price of all categories.
SELECT 
    rm.RoomNumber,
    rc.CategoryName,
    rc.BasePrice,
    (SELECT AVG(BasePrice) FROM RoomCategories) AS OverallAveragePrice
FROM 
    Rooms rm
INNER JOIN 
    RoomCategories rc ON rm.CategoryID = rc.CategoryID;
GO
